- name: Provision DirectAdmin user and email services
  block:

    # 1. Query existing DirectAdmin users
    - name: Query existing DirectAdmin users
      uri:
        url: "{{ directadmin_api_url }}/CMD_API_SHOW_USERS"
        method: GET
        user: "{{ directadmin_api_username }}"
        password: "{{ directadmin_api_key }}"
        force_basic_auth: yes
        return_content: yes
      register: user_list

    # 2. Parse user list from URL-encoded string to list
    - name: Parse DirectAdmin user list
      set_fact:
        user_list_parsed: >-
          {{
            user_list.content
            | community.general.from_urlencoded
            | dict2items
            | map(attribute='value')
            | list
          }}

    # 3. Query existing DirectAdmin domains
    - name: Query existing DirectAdmin domains
      uri:
        url: "{{ directadmin_api_url }}/CMD_API_SHOW_DOMAINS"
        method: GET
        user: "{{ directadmin_api_username }}"
        password: "{{ directadmin_api_key }}"
        force_basic_auth: yes
        return_content: yes
      register: domain_list

    # 4. Parse domain list from URL-encoded string to list
    - name: Parse DirectAdmin domain list
      set_fact:
        domain_list_parsed: >-
          {{
            domain_list.content
            | community.general.from_urlencoded
            | dict2items
            | map(attribute='value')
            | list
          }}

    # 5. Fail if the user already exists
    - name: Fail if DirectAdmin user already exists
      fail:
        msg: "DirectAdmin user {{ username }} already exists. Aborting playbook."
      when: username in user_list_parsed

    # 6. Fail if the domain already exists
    - name: Fail if DirectAdmin domain already exists
      fail:
        msg: "DirectAdmin domain {{ domain }} already exists. Aborting playbook."
      when: domain in domain_list_parsed

    # ---- Continue with the rest of your tasks here ----


    # 2. Load password if user exists, else generate new one
    - name: Load DirectAdmin password from file (if user exists)
      set_fact:
        directadmin_user_password: "{{ lookup('file', './output/{{ username }}_creds.txt') | regex_search('DirectAdmin Password: (.*)', '\\1') }}"
      when: username in user_list.content
      ignore_errors: true

    - name: Generate strong password for new user (if needed)
      set_fact:
        directadmin_user_password: "{{ lookup('password', '/dev/null length=24 chars=ascii_letters,digits,special') }}"
      when: username not in user_list.content

    - name: Show selected DirectAdmin password
      debug:
        msg: "Using password for user {{ username }}: {{ directadmin_user_password }}"

    # 3. Save credentials (if new)
    - name: Save new DirectAdmin user credentials
      copy:
        dest: "./output/{{ username }}_creds.txt"
        content: |
          Username: {{ username }}
          Domain: {{ domain }}
          Email: {{ email }}
          DirectAdmin Password: {{ directadmin_user_password }}

          {% if create_email_accounts | default(false) and email_accounts_with_passwords is defined %}
          Mailboxes:
          {% for account in email_accounts_with_passwords %}
          - {{ account.user }}@{{ domain }}: {{ account.pass }}
          {% endfor %}
          {% endif %}
      when: username not in user_list.content

    # 4. Create user if not present
    - name: Create DirectAdmin user
      uri:
        url: "{{ directadmin_api_url }}/CMD_API_ACCOUNT_USER"
        method: POST
        user: "{{ directadmin_api_username }}"
        password: "{{ directadmin_api_key }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        return_content: yes
        body:
          action: create
          add: 'yes'
          username: "{{ username }}"
          email: "{{ email }}"
          passwd: "{{ directadmin_user_password }}"
          passwd2: "{{ directadmin_user_password }}"
          domain: "{{ domain }}"
          package: "{{ package }}"
          ip: "{{ ip }}"
        status_code: 200
      when: username not in user_list.content and not safe_mode | default(false)
      register: user_result
      failed_when: false
      tags: create_user

    - name: Show user creation result
      debug:
        var: user_result.content
      when: user_result is defined

    - name: Wait for DirectAdmin to finish provisioning user
      pause:
        seconds: 5

    # 5. Prepare email accounts with random passwords (if needed)
    - name: Generate strong passwords for email accounts
      set_fact:
        email_accounts_with_passwords: >-
          {{
            email_accounts | map('combine', {
              'pass': lookup('password', '/dev/null length=20 chars=ascii_letters,digits,special')
            }) | list
          }}
      when: email_accounts is defined and email_accounts | length > 0

    # 6. Create email accounts if enabled
    - name: Create email accounts via API
      uri:
        url: "{{ directadmin_api_url }}/CMD_API_POP"
        method: POST
        user: "{{ username }}"
        password: "{{ directadmin_user_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          action: create
          domain: "{{ domain }}"
          user: "{{ item.user }}"
          passwd: "{{ item.pass }}"
          passwd2: "{{ item.pass }}"
          quota: 5000
      loop: "{{ email_accounts_with_passwords }}"
      loop_control:
        label: "{{ item.user }}@{{ domain }}"
      register: email_results
      when:
        - create_email_accounts | default(false)
        - email_accounts_with_passwords is defined
        - not safe_mode | default(false)
      tags: create_mail

    - name: Show email creation results
      debug:
        var: email_results

    # 7. DKIM setup
    - name: Check if DKIM public key exists
      stat:
        path: "/etc/virtual/{{ domain }}/dkim.public.key"
      register: dkim_key
      delegate_to: "{{ directadmin_host | default('localhost') }}"

    - name: Enable DKIM via API (if not already enabled)
      uri:
        url: "{{ directadmin_api_url }}/CMD_API_EMAIL_DKIM?action=enable&domain={{ domain }}"
        method: GET
        user: "{{ username }}"
        password: "{{ directadmin_user_password }}"
        force_basic_auth: yes
        status_code: 200
      when: not dkim_key.stat.exists and not safe_mode | default(false)
      register: dkim_result
      failed_when: false
      tags: enable_dkim

    - name: Show DKIM enable result
      debug:
        var: dkim_result

    # 8. (Optional) Check for and create only missing mailboxes
    - name: Get current mailboxes (for idempotency)
      uri:
        url: "{{ directadmin_api_url }}/CMD_API_POP?domain={{ domain }}"
        method: GET
        user: "{{ username }}"
        password: "{{ directadmin_user_password }}"
        force_basic_auth: yes
        return_content: yes
      register: mailbox_list
      when: create_email_accounts | default(false)

    - name: Identify missing mailboxes
      set_fact:
        mailboxes_to_create: >-
          {{
            email_accounts_with_passwords
            | rejectattr(
                'user',
                'in',
                (
                  mailbox_list.content
                  | community.general.from_urlencoded
                  | dict2items
                  | selectattr('key', 'search', '^list\\d+$')
                  | map(attribute='value')
                  | list
                )
              )
          }}
      when: create_email_accounts | default(false) and mailbox_list is defined

    - name: Create only missing email accounts
      uri:
        url: "{{ directadmin_api_url }}/CMD_API_POP"
        method: POST
        user: "{{ username }}"
        password: "{{ directadmin_user_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          action: create
          domain: "{{ domain }}"
          user: "{{ item.user }}"
          passwd: "{{ item.pass }}"
          passwd2: "{{ item.pass }}"
          quota: 5000
      loop: "{{ mailboxes_to_create | default([]) }}"
      loop_control:
        label: "{{ item.user }}@{{ domain }}"
      register: email_results
      when:
        - create_email_accounts | default(false)
        - mailboxes_to_create is defined and mailboxes_to_create | length > 0
        - not safe_mode | default(false)
      tags: create_mail

