---
# playbooks/full_onboarding.yml
- name: Full Onboarding for Web Hosting Client
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "../clients/client01.yml"
    - "../group_vars/all.yml"

  roles:
    - role: directadmin
    - role: cloudflare
  # - role: monitoring

