- name: Check if Cloudflare zone exists
  uri:
    url: "https://api.cloudflare.com/client/v4/zones?name={{ domain }}"
    method: GET
    headers:
      Authorization: "Bearer {{ cloudflare_api_token }}"
      Content-Type: "application/json"
    return_content: yes
  register: cloudflare_zone_check

- name: Set zone_id if zone exists
  set_fact:
    zone_exists: "{{ cloudflare_zone_check.json.result | length > 0 }}"
    zone_id: "{{ cloudflare_zone_check.json.result[0].id if cloudflare_zone_check.json.result | length > 0 else '' }}"

- name: Create Cloudflare zone via API if not exists
  uri:
    url: "https://api.cloudflare.com/client/v4/zones"
    method: POST
    headers:
      Authorization: "Bearer {{ cloudflare_api_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      name: "{{ domain }}"
      jump_start: false
    status_code: 200
  register: zone_create_result
  when: not zone_exists and not safe_mode | default(false)
  failed_when: false

- name: Re-fetch zone ID after creation
  uri:
    url: "https://api.cloudflare.com/client/v4/zones?name={{ domain }}"
    method: GET
    headers:
      Authorization: "Bearer {{ cloudflare_api_token }}"
      Content-Type: "application/json"
    return_content: yes
  register: cloudflare_zone_check_fresh
  when: not zone_exists

- name: Set final zone_id
  set_fact:
    zone_id: "{{ cloudflare_zone_check_fresh.json.result[0].id }}"
  when: not zone_exists

- name: Get existing DNS records from Cloudflare
  uri:
    url: "https://api.cloudflare.com/client/v4/zones/{{ zone_id }}/dns_records"
    method: GET
    headers:
      Authorization: "Bearer {{ cloudflare_api_token }}"
      Content-Type: "application/json"
    return_content: yes
  register: existing_dns_records
  when: zone_id is defined

- name: Create or remove DNS records in Cloudflare
  community.general.cloudflare_dns:
    api_token: "{{ cloudflare_api_token }}"
    zone: "{{ domain }}"
    type: "{{ item.type }}"
    record: "{{ item.name }}"
    value: "{{ item.value }}"
    ttl: "{{ item.ttl }}"
    proxied: "{{ item.proxied | default(omit) }}"
    priority: "{{ item.priority | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ cloudflare_dns_records }}"
  when:
    - zone_id is defined
    - not safe_mode | default(false)
