- name: Get Cloudflare Zone ID
  uri:
    url: "https://api.cloudflare.com/client/v4/zones"
    method: GET
    headers:
      Authorization: "Bearer {{ cloudflare_api_token }}"
      Content-Type: "application/json"
    return_content: yes
  register: cloudflare_zones

- name: Set Zone ID Fact
  set_fact:
    zone_id: "{{ cloudflare_zones.json.result | selectattr('name', 'equalto', cloudflare_zone) | map(attribute='id') | first }}"

- name: Create A Record
  uri:
    url: "https://api.cloudflare.com/client/v4/zones/{{ zone_id }}/dns_records"
    method: POST
    headers:
      Authorization: "Bearer {{ cloudflare_api_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      type: "A"
      name: "{{ domain }}"
      content: "{{ ip }}"
      ttl: 3600
      proxied: false
    status_code: 200
